[package]
name = "bevy_networking_minimal_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_crab_networking = { path = "../bevy_crab_networking" }
bevy = "0.14.2"
serde = "1.0.210"
serde_derive = "1.0.210"
bincode = "1.3.3"
